# The workflow runs when we create a release in github.
# The workflow will build the android package and push it to github package.

name: Publish Android Artifact

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      GH_PERSONAL_ACCESS_TOKEN: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
      TAG: ${{ github.event.release.tag_name }}

    steps:
      # Checkout
      - name: Checkout
        uses: actions/checkout@v3

      # Set up JDK
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: 17

      # Setup Flutter
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.19.6
          cache: true

      # Set Execute permission to script directory
      - name: Set Execute permission to script directory
        run: chmod -R +x .github/scripts

      # Validate Tag
      - name: Validate Tag
        run: .github/scripts/publish/validate_tag.sh

      # Publish Android Module
      - name: Publish Android Module
        run: .github/scripts/publish/publish_android_module.sh

      # Publish Pigeon Jar
      - name: Publish Pigeon Jar
        run: .github/scripts/publish/publish_pigeon_jar.sh
